config/routes.rb
PartyTime::Application.routes.draw do
  resources :pages
  root 'pages#index'

  

end

app/models/page.rb
class Page < ActiveRecord::Base

	def self.party(photo)
		photo ||= "boogermanloop"

		auth = { query: { client_id: 'c77ea186e7a4465a90729e3c4735403a' }}
				
		search_url = "https://api.instagram.com/v1/tags/#{photo.delete(" ")}/media/recent"
		
		response = HTTParty.get search_url, auth

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 
  def index
    # @photo = HTTParty.get "https://api.instagram.com/v1/tags/abramsfalls/media/recent?client_id=c77ea186e7a4465a90729e3c4735403a"
    @photo = Page.party(params[:photo])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PartyTime</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Trail Search</h1>

<%= form_tag pages_path, :method => 'get' do %>
    <%= text_field_tag :photo, params[:photo] %>
    <%= submit_tag "Search", :name => nil %>
<% end %>
<br>
Not sure which trail you want? Try <%= link_to "Boogerman Loop" , pages_path(photo: "boogermanloop") %>

<hr>

<h2><%= @photo["data"][0]["caption"]["text"] %></h2>
<%= image_tag @photo["data"][0]["images"]["thumbnail"]["url"] %>

<br>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @page.url %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>